import { Car } from './car';

export const CARS: Car[] = [
    {
        id: 1,
        make: 'BMW',
        model: 'M4',
        year: '2021',
        description: 'With a radical design and up to 503 horsepower, the new BMW M4 coupe marks a notable departure in both looks and performance from its two-door predecessor.',
        image: '../assets/img/car-on-sale/bmw-m4-2021.jpg',
        price: 72500,
    },
    {
        id: 2,
        make: 'Mercedes-Benz',
        model: 'A Class',
        year: '2022',
        description: 'Distilling a luxury brands ethos down to an affordable entry-level sedan is a task wrought with compromise, but the Mercedes-Benz A-class pulls it off.',
        image: '../assets/img/car-on-sale/mercedes-benz-a-class-2022.jpg',
        price: 35000,
    },
    {
        id: 3,
        make: 'Porsche',
        model: '718 Cayman',
        year: '2022',
        description: 'Its not the most practical choice, but the 2022 Porsche 718 Cayman captures the same physical and emotional excitement of driving as a supercar does.',
        image: '../assets/img/car-on-sale/porsche-718cayman-2022.jpg',
        price: 61000,
    },
    {
        id: 4,
        make: 'Lamborghini',
        model: 'Aventador',
        year: '2020',
        description: 'With wild styling and a naturally aspirated V-12 engine, the 2020 Lamborghini Aventador is a flamboyant send-off to unadulterated supercars.',
        image: '../assets/img/car-on-sale/lamborghini-aventador-2020.jpg',
        price: 425000,
    },
    {
        id: 5,
        make: 'Ferrari',
        model: 'Roma',
        year: '2022',
        description: 'For everyone who forgot, the Ferrari Roma reminds them that the Italian automaker still knows how to make a pretty front-engine coupe thats great to drive.',
        image: '../assets/img/car-on-sale/ferrari-roma-2022.jpg',
        price: 226000,
    },
    {
        id: 6,
        make: 'Rolls-Royce',
        model: 'Ghost',
        year: '2019',
        description: 'For those who desire sybaritic luxury and a spirited driving experience in the same ultra-pricey motorcar, the 2019 Rolls-Royce Ghost Series II is your answer.',
        image: '../assets/img/car-on-sale/rolls-royce-ghost-2019.jpg',
        price: 314400,
    },
];