import { User } from "./User";

export const USERS: User[] = [
    {
        id: 1,
        firstName: 'Barry',
        lastName: 'Portillo',
        company: 'Google',
        city: 'Jakarta',
        country: 'Indonesia',
        email: 'barry@abc.com',
        password: 'barry123',
        imageProfile: '../assets/img/user/barry.jpg',
    },
    {
        id: 2,
        firstName: 'Jannat',
        lastName: 'Hamilton',
        company: 'Google',
        city: 'Tokyo',
        country: 'Japan',
        email: 'jannat@abc.com',
        password: 'jannat123',
        imageProfile: '../assets/img/user/jannat.jpg',
    },
    {
        id: 3,
        firstName: 'Aniyah',
        lastName: 'Hayden',
        company: 'Samsung',
        city: 'Bandung',
        country: 'Indonesia',
        email: 'aniyah@abc.com',
        password: 'aniyah123',
        imageProfile: '../assets/img/user/aniyah.jpg',
    },
    {
        id: 4,
        firstName: 'Elliot',
        lastName: 'Hogan',
        company: 'Amazon',
        city: 'New York',
        country: 'USA',
        email: 'elliot@abc.com',
        password: 'elliot123',
        imageProfile: '../assets/img/user/elliot.jpg',
    },
    {
        id: 5,
        firstName: 'Howard',
        lastName: 'Richards',
        company: 'Microsoft',
        city: 'Berlin',
        country: 'German',
        email: 'howard@abc.com',
        password: 'howard123',
        imageProfile: '../assets/img/user/howard.jpg',
    },
];